[build-system]
equires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "api-test"
version = "0.1.0"
dependencies = [
  "fastapi"
]
[project.scripts]
spam-cli = "api:root"
