[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "api-test"
version = "0.1.0"
dependencies = [
  "fastapi"
]

[project.scripts]
api = "api:root"
