# deployed on oraclecloud.com with `nlb`
# 
# sdake@wise-00:~/work/api-test/kubernetes$ curl 129.153.64.58:80
# {"model_names":["ibm-granite/granite-34b-code-instruct","ibm-granite/granite-34b-code"]}
---
apiVersion: v1
kind: Service
metadata:
  name: models
  annotations:
    oci-network-load-balancer.oraclecloud.com/security-list-management-mode: "All"
    oci.oraclecloud.com/load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: models
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: models
  labels:
    app: models
spec:
  replicas: 3
  selector:
    matchLabels:
      app: models
  template:
    metadata:
      labels:
        app: models
    spec:
      containers:
      - name: models
        image: docker.io/sdake/test-api:v0.1.1
        ports:
        - containerPort: 8080
